@startmindmap
*  ML机器学习

** Basic
*** 线性代数
*** 概率与信息论
*** 高等数学
*** 数值计算


** ML机器学习
*** ML基础
**** T P E
**** 过拟合和欠拟合
**** 超参数和验证集
**** 估计 偏差 方差
***** >最大似然估计
***** >贝叶斯统计

**** 随机梯度下降

**** 促进DL学习发展的挑战
***** 维数灾难
***** 局部不变和平滑regulation
***** 流行学习

*** 有监督
**** 线性回归
**** 逻辑回归
**** SVM支持向量机
**** 决策树 随机森林
**** 朴素贝叶斯
**** KNN
**** 神经网络

*** 无监督
**** PCA
**** LDA
**** k-means
**** 混合高斯分布
**** t-SNE

** DL深度学习
*** 前馈网络
*** Regulation
*** Optimization
*** CNN
*** RNN
*** 实操技巧
*** 应用部署


** Research
*** 线性因子模型
*** 自编码器
*** 表示学习
*** 结构化概率模型
*** 蒙特卡罗方法
*** 直面配分函数
*** 近似推断
*** 深度生成模型



@endmindmap